package asterixorobelix.afrikaburn.models

class DatabaseProject : DatabaseProjectable {
    override var nid: String? = ""
    override var type: String? = ""
    var title: String? = ""
    var fieldCollective: String? = ""
    var fieldPrjWtfShortCopy: String? = ""
    var fieldPrjWtfLong: String? = ""
    var fieldPrjWtfPlanned: String? = ""
    var fieldPrjWtfCategories: String? = ""
    var fieldPrjWtfScheduled: String? = ""
    var fieldPrjWtfImage: String? = ""
    var fieldPrjGenHistory: String? = ""
    var fieldPrjWtfWebsite: String? = ""
    var fieldPrjOthRelationship: String? = ""
    var fieldPrjOthAssociated: String? = ""
    var fieldPrjBrnBurning: String? = ""
    var fieldPrjBrnTimeAdm: String? = ""
    var fieldPrjSndSound: String? = ""
    var fieldPrjSndLevel: String? = ""
    var fieldPrjAdmLatitude: String? = ""
    var fieldPrjAdmLongitude: String? = ""
    var fieldAPIContentType: String? = ""
}